### ISSUE TITLE
typeerror: cannot read property 'load' of null

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflare-gcp#18] opened 2019-05-01 08:22 UTC
After deploying this in a clean project I get this from the Cloud Function when it runs:
resource: {…}  
 severity:  "ERROR"  
 textPayload:  "TypeError: Cannot read property 'load' of null
    at dataset.table.get (/srv/index.js:32:13)
    at onCreate (/srv/node_modules/@google-cloud/common/build/src/service-object.js:153:17)
    at onCreate (/srv/node_modules/@google-cloud/common/build/src/service-object.js:109:13)
    at request (/srv/node_modules/@google-cloud/bigquery/build/src/dataset.js:365:17)
    at Util.handleResp (/srv/node_modules/@google-cloud/common/build/src/util.js:141:9)
    at retryRequest (/srv/node_modules/@google-cloud/common/build/src/util.js:422:22)
    at onResponse (/srv/node_modules/retry-request/index.js:200:7)
    at /srv/node_modules/teeny-request/build/src/index.js:222:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"  
 timestamp:  "2019-05-01T08:18:11.571Z"  

The storage bucket is in US region nearline storage and the region chosen for the deployment is us-central1.
It does not create the BigQuery datasets.

**Comment by shagamemnon** [comment] 2019-05-01 17:27
Hey @vidarak sorry to you're having issues. Can you share the region you're using for nearline storage? Also, do you have BigQuery tables already created? Or were you anticipating that the tables would be created for you (the expected behavior is that the tables are created automatically, so either way you shouldn't be running into issues)?

We have not tested this when using a storage bucket with nearline storage, only multi-region storage, so your feedback is welcomed

**Comment by vidarak** [comment] 2019-05-01 20:06
Storage is US region. I don't have anything created under BigQuery. The function keeps executing so it seems like its able to read from the storage. Problem seems to be related to creating tables for BigQuery. The logs pushed from Cloudflare have all fields possibly selected with RFC 3339 timeformat

**Comment by vidarak** [comment] 2019-05-06 08:29
I tried changing the storage bucket to multi-regional but the function still gives the same error for new files written as "multi-regional".

**Comment by tmayr** [comment] 2019-05-08 14:51
Apparently it's because theres no dataset created under BigQuery, just go ahead and create a "cloudflare_logs" under that and the table should be created automatically.

I'm guessing it's because the script creates the tables automatically, but since the DataSet isn't created, it just fails.

Cheers

**Comment by shagamemnon** [comment] 2019-05-13 19:02
@vidarak @tmayr is correct – the dataset is not being created automatically per https://cloud.google.com/nodejs/docs/reference/bigquery/3.0.x/Dataset#create. This will be fixed today

**Closed** 2019-05-13 23:48 UTC
